---
title: "hw_3"
output: html_notebook
---
### 1.1

```{r}
library(tidyverse)
library(mosaic)
library(ggplot2)
```

```{r}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data <- read_csv('https://github.com/headshoter13/2018_hse_data_analysis/raw/master/hw3_binomial/hw3_binomial.csv')

```

```{r}
binomial_test <- binom.test(x = data$k, n = data$n, p = data$prior)
binomial_test
```
### 1.2
```{r}
set.seed(42)
do(1000)*
  sum(sample(x = 1:0, 
             size = data$n, 
             prob = c(data$prior, 1 - data$prior), 
             replace = TRUE)) ->
  simulations

simulations %>% 
  mutate(greater = sum >= data$k) %>% 
  count(greater)

```

### 1.3
```{r}
alpha_prior <- data$prior * data$n
alpha_post <- alpha_prior + data$k
beta_prior <- (1-data$prior) * data$n
beta_post <- beta_prior + (data$n - data$k)

alpha_post/(alpha_post+beta_post)
```

### 1.4
```{r}
alpha_noinfo <- 1 + data$k
beta_noinfo <- 1 + (data$n - data$k)
alpha_noinfo/(alpha_noinfo+beta_noinfo)
```

### 1.5
По результатам биномиального теста мы получили
p-value = 0.6842 ->  гиотеза не отвергается

Что касается апостериорного распределения, то мы имее практически равные значения 0.3084925 и 0.300885.


