---
title: "hw_4"
output: html_notebook
---
### 1.1
```{r}
library(tidyverse)
library(mosaic)
library(bootstrap)
```



```{r}
data <- read_csv('https://github.com/headshoter13/2018_hse_data_analysis/raw/master/hw4_binomial_ci/hw4_wodehouse.csv')
```

```{r}
data %>% 
  group_by(chapter) %>%
  mutate(n_words=n()) %>%
  group_by(chapter, n_words, word) %>%
  summarize(n=n()) %>% 
  filter(word == "сэр") %>% 
  ungroup() %>%
  mutate(average = n/n_words) ->
  sir

as_tibble(sir)
```

```{r}
grand_mean <- summarise(sir, g_mean=mean(average))
```

### 1.2

```{r}
bts_bs <- bootstrap(sir$average, nboot = 10000, theta = mean)$thetastar
#bts_bs <- data_frame(means = bts_bs)

group_bs <- tibble(mean=mean(bts_bs),
                q = quantile(bts_bs, 0.025),
                q1 = quantile(bts_bs, 0.975))

tibble(group=group_bs$q - group_bs$q1)
as_tibble(bts_bs)
```

### 1.3

```{r}
sir %>%
  group_by(chapter) %>%
  mutate(ci_binom = binom.test(x = n, n = n_words, ci.method = "Clopper-Pearson")$conf.int[2] -
                    binom.test(x = n, n = n_words, ci.method = "Clopper-Pearson")$conf.int[1]) %>%
  ungroup()%>%
  as_tibble() -> sir

sir %>%
  filter(ci_binom == max(ci_binom)) %>%
  select(chapter,ci_binom) ->
  ci_max_binom

as_tibble(ci_max_binom)
```

### 1.4
```{r}
mu <- mean(sir$average)
var <- var(sir$average)
alpha0 <- ((1 - mu) / var - 1 / mu) * mu ^ 2
beta0 <- alpha0 * (1 / mu - 1)

sir %>% 
  group_by(chapter) %>% 
  mutate(alpha_post = n + alpha0,
         beta_post = n_words - n + beta0,
         average_post = alpha_post/(alpha_post+beta_post),
         cred_int_l = qbeta(.025, alpha_post, beta_post),
         cred_int_h = qbeta(.975, alpha_post, beta_post),
         bayes_ci = cred_int_h - cred_int_l) ->
  sir_bayes
```

```{r}
sir_bayes %>%
  select(chapter, n_words, average, average_post, bayes_ci) %>% 
  arrange(n_words)

as_tibble(sir_bayes[which.max(sir_bayes$bayes_ci),])

```

### 1.5
```{r}
sir %>%
  filter(ci_binom == min(ci_binom)) %>%
  select(chapter, ci_binom) ->
  ci_binom_min

as_tibble(ci_binom_min)
```

### 1.6
```{r}
sir_bayes[which.min(sir_bayes$cred_int_h - sir_bayes$cred_int_l),]['chapter'] -> chapter_needed
chapter_needed
```

